[project]
name = "Rlm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=2.15.0",
    "tiktoken>=0.12.0",
    "xai-sdk>=1.5.0",
]
